### ISSUE TITLE
Need branch protections for `main`

### ISSUE THREAD

**Issue by jeroenminderman** [tech-acs/crvs_report#8]
Suggest we add branch protections for `main`, ie require PR before merges

@tbelay @gulilattesfaye @beardl-ons @rcatlord @diego-ons

**Comment by tbelay** [comment]
Branch protection rule set for crvsreportpackage with Diego & Henry bypass privilege. 
@jeroenminderman @rcatlord @diego-ons @beardl-ons  @gulilattesfaye

**Comment by jeroenminderman** [comment]
Thank you @tbelay! I was referring to specifically this repo ([https://github.com/tech-acs/crvs_report](https://github.com/tech-acs/crvs_report)) though. Happy to set this myself if you're happy with that - I can now access settings.

**Comment by jeroenminderman** [comment]
I've now done this for [main](https://github.com/tech-acs/crvs_report) for this repo as well.
Repo/org admins can bypass by default, I believe.
